# Generated by Django 4.1.5 on 2023-01-31 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(blank=True, choices=[('อบรมและทบทวน', 'อบรมและทบทวน'), ('อบรมเท่านั้น', 'อบรมเท่านั้น'), ('ทบทวนเท่านั้น', 'ทบทวนเท่านั้น')], max_length=200, null=True)),
                ('generation', models.CharField(blank=True, max_length=200, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('earlybird_date_start', models.DateField(blank=True, null=True)),
                ('earlybird_date_end', models.DateField(blank=True, null=True)),
                ('price_earlybird', models.BigIntegerField(blank=True, null=True)),
                ('promotion_date_start', models.DateField(blank=True, null=True)),
                ('promotion_date_end', models.DateField(blank=True, null=True)),
                ('price_promotion', models.BigIntegerField(blank=True, null=True)),
                ('fullprice_date_start', models.DateField(blank=True, null=True)),
                ('fullprice_date_end', models.DateField(blank=True, null=True)),
                ('price_fullprice', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagecourse/')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('jobs', models.CharField(blank=True, max_length=200, null=True)),
                ('haveaccout', models.BooleanField(blank=True, default=None, null=True)),
                ('oldaccout', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('receipt', models.CharField(blank=True, choices=[('นามบุคคล', 'นามบุคคล'), ('นามองค์กร', 'นามองค์กร')], max_length=200, null=True)),
                ('indiname', models.CharField(blank=True, max_length=200, null=True)),
                ('indilastname', models.CharField(blank=True, max_length=200, null=True)),
                ('inditaxid', models.BigIntegerField(blank=True, default=0, null=True)),
                ('indiaddress', models.CharField(blank=True, max_length=200, null=True)),
                ('indicity', models.CharField(blank=True, max_length=200, null=True)),
                ('indistate', models.CharField(blank=True, max_length=200, null=True)),
                ('indipostal', models.CharField(blank=True, max_length=200, null=True)),
                ('indicountry', models.CharField(blank=True, max_length=200, null=True)),
                ('indiaddress_send', models.CharField(blank=True, max_length=200, null=True)),
                ('indicity_send', models.CharField(blank=True, max_length=200, null=True)),
                ('indistate_send', models.CharField(blank=True, max_length=200, null=True)),
                ('indipostal_send', models.CharField(blank=True, max_length=200, null=True)),
                ('indicountry_send', models.CharField(blank=True, max_length=200, null=True)),
                ('orgname', models.CharField(blank=True, max_length=200, null=True)),
                ('orgaddress1', models.CharField(blank=True, max_length=200, null=True)),
                ('orgaddress2', models.CharField(blank=True, max_length=200, null=True)),
                ('orgcity', models.CharField(blank=True, max_length=200, null=True)),
                ('orgstate', models.CharField(blank=True, max_length=200, null=True)),
                ('orgpostal', models.CharField(blank=True, max_length=200, null=True)),
                ('orgcountry', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('orgaddress1_send', models.CharField(blank=True, max_length=200, null=True)),
                ('orgaddress2_send', models.CharField(blank=True, max_length=200, null=True)),
                ('orgcity_send', models.CharField(blank=True, max_length=200, null=True)),
                ('orgstate_send', models.CharField(blank=True, max_length=200, null=True)),
                ('orgpostal_send', models.CharField(blank=True, max_length=200, null=True)),
                ('orgcountry_send', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('orgtaxid', models.BigIntegerField(blank=True, default=0, null=True)),
                ('taxwithholding', models.CharField(blank=True, max_length=200, null=True)),
                ('acctype', models.CharField(blank=True, max_length=200, null=True)),
                ('imageevidence', models.ImageField(blank=True, null=True, upload_to='imageevidence/')),
                ('imageevidence_data', models.BinaryField(blank=True, null=True)),
                ('paymenttype', models.CharField(blank=True, choices=[('เงินโอน', "ชำระด้วย'เงินโอน'"), ('บัตรเครดิต', "ชำระด้วย'บัตรเครดิต'"), ('Voucher', 'ใช้ Voucher')], max_length=200, null=True)),
                ('paywithvoucher', models.CharField(blank=True, choices=[('เงินโอน', "ชำระด้วย'เงินโอน'"), ('บัตรเครดิต', "ชำระด้วย'บัตรเครดิต'"), ('', '')], max_length=200, null=True)),
                ('imagevoucherevidence', models.ImageField(blank=True, null=True, upload_to='imagevoucherevidence/')),
                ('imagevoucherevidence_data', models.BinaryField(blank=True, null=True)),
                ('acceptall', models.BooleanField(blank=True, default=None, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('channel', models.ManyToManyField(to='app_general.channelmodel')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.classroommodel')),
            ],
        ),
        migrations.AddField(
            model_name='classroommodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.coursemodel'),
        ),
    ]
