# Generated by Django 4.1.5 on 2023-02-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='titlename',
            field=models.CharField(blank=True, choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว'), ('อื่นๆ', 'อื่นๆ')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='titlename_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='acctype',
            field=models.CharField(blank=True, choices=[('บุคคลทั่วไป', 'บุคคลทั่วไป'), ('สมาชิกสมาคม', 'สมาชิกสมาคม'), ('นิสิต/นักศึกษา', 'นิสิต/นักศึกษา')], max_length=200, null=True),
        ),
    ]
