# Generated by Django 4.1.5 on 2023-02-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0002_registermodel_titlename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
