# Generated by Django 4.1.5 on 2023-02-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0004_remove_coursemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='order_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
