# Generated by Django 4.1.5 on 2023-02-08 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0005_coursemodel_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(blank=True, max_length=200, null=True)),
                ('margin', models.BigIntegerField(blank=True, null=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.classroommodel')),
            ],
        ),
    ]
