# Generated by Django 4.1.5 on 2023-02-08 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0006_vouchermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchermodel',
            name='classroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.classroommodel'),
        ),
    ]
