# Generated by Django 4.1.5 on 2023-02-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0007_alter_vouchermodel_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='order_number',
        ),
        migrations.AddField(
            model_name='classroommodel',
            name='product_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
