# Generated by Django 4.1.5 on 2023-02-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0008_remove_coursemodel_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='order_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
