# Generated by Django 4.1.5 on 2023-02-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0009_coursemodel_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
