# Generated by Django 4.1.5 on 2023-02-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0010_registermodel_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='imageevidence_data',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='imagevoucherevidence_data',
        ),
    ]
