# Generated by Django 4.1.5 on 2023-02-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0011_remove_registermodel_imageevidence_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
